name: maven-build-ci
on: 
  push: 
    branches:
      - main
jobs:
  build: 
    #runs-on: ubuntu-latest (public)
    runs-on: devops-runner   #self-hosted
    steps: 
      - name: checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=maven-dev
          
      - name: build-maven
        run: mvn clean package  

      - name: list 
        run: ls -l target/
      - name: Nexus Repo Publish
        uses: sonatype-nexus-community/nexus-repo-github-action@master
        with:
          serverUrl: ${{ secrets.NEXUS_HOST_URL }}
          username: admin
          password: ${{ secrets.NEXUS_PASSWORD }}
          format: maven2
          repository: maven-demo
          coordinates: groupId=com.efsavage artifactId=hello-world-war version=1.1.4
          assets: extension=war
          filename: ./target/*.war

      - name: Deploy WAR to Tomcat
        run: |
          curl --version
          ls -l
          # Replace 'your-war-file.war' with the actual name of your WAR file
          curl -v -u admin:${{ secrets.TOMCAT_PASSWORD }} -T target/*.war 'http://${{ secrets.TOMCAT_HOST }}:8080/manager/text/deploy?path=/devops_demo1&update=true'